name: CI - Build and Push nginx-app

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: thorntoncloud/nginx-gitops

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "full_image=${DOCKER_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx-app
          file: ./nginx-app/Dockerfile
          push: false
          load: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.sha }}
            ${{ env.DOCKER_IMAGE }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.sha }}
          format: 'table'

      - name: Run Trivy vulnerability scanner (SARIF output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.sha_tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ steps.tag.outputs.sha }}
          docker push ${{ env.DOCKER_IMAGE }}:latest